name: build
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install pipenv 
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev pytest-cov
      - name: Run test suite
        run: |
          pipenv run pytest --cov
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Run black formatter
        uses: rickstaa/action-black@v1.3.3
            